### ISSUE TITLE
Error With SonarQube OJAudit plugin

### ISSUE THREAD

**Issue by wvanderdeijl** [adfemg/sonarqube-ojaudit#4]
_issue migrated from https://java.net/jira/browse/SONARQUBE_OJAUDIT-6_

I have my own rules created with Audit Rules, after that i tried to integrate the file "rulehelp.txt" in SonarQube but i got this error:
error:

```
2014.03.06 14:15:34 ERROR o.s.s.p.PlatformLifecycleListener Fail to start server
org.sonar.api.utils.SonarException: The following rule (repository: ojaudit) must have a name: Rule[id=<null>,name=<null>,key=<null>,configKey=<null>,plugin=ojaudit,severity=MAJOR,cardinality=SINGLE,status=READY,language=ojaudit,parent=<null>]
at org.sonar.server.startup.RegisterRules.validateRuleRepositoryName(RegisterRules.java:157) ~[RegisterRules.class:na]
at org.sonar.server.startup.RegisterRules.validateRule(RegisterRules.java:151) ~[RegisterRules.class:na]
at org.sonar.server.startup.RegisterRules.registerRepositoryRules(RegisterRules.java:105) ~[RegisterRules.class:na]
at org.sonar.server.startup.RegisterRules.registerRules(RegisterRules.java:92) ~[RegisterRules.class:na]
at org.sonar.server.startup.RegisterRules.start(RegisterRules.java:71) ~[RegisterRules.class:na]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.6.0_37]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39) ~[na:1.6.0_37]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) ~[na:1.6.0_37]
at java.lang.reflect.Method.invoke(Method.java:597) ~[na:1.6.0_37]
at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.invokeMethod(ReflectionLifecycleStrategy.java:110) ~[picocontainer-2.14.3.jar:na]
at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.start(ReflectionLifecycleStrategy.java:91) ~[picocontainer-2.14.3.jar:na]
at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.start(AbstractInjectionFactory.java:85) ~[picocontainer-2.14.3.jar:na]
at org.picocontainer.behaviors.AbstractBehavior.start(AbstractBehavior.java:169) ~[picocontainer-2.14.3.jar:na]
at org.picocontainer.behaviors.Stored$RealComponentLifecycle.start(Stored.java:133) ~[picocontainer-2.14.3.jar:na]
at org.picocontainer.behaviors.Stored.start(Stored.java:111) ~[picocontainer-2.14.3.jar:na]
at org.picocontainer.DefaultPicoContainer.potentiallyStartAdapter(DefaultPicoContainer.java:1015) ~[picocontainer-2.14.3.jar:na]
at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1008) ~[picocontainer-2.14.3.jar:na]
at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:767) ~[picocontainer-2.14.3.jar:na]
at org.sonar.api.platform.ComponentContainer.startComponents(ComponentContainer.java:92) ~[sonar-plugin-api-4.0.jar:na]
at org.sonar.server.platform.Platform.executeStartupTasks(Platform.java:400) ~[Platform.class:na]
at org.sonar.server.platform.Platform.start(Platform.java:203) ~[Platform.class:na]
at org.sonar.server.platform.PlatformLifecycleListener.contextInitialized(PlatformLifecycleListener.java:36) ~[PlatformLifecycleListener.class:na]
at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4939) ~[tomcat-embed-core-7.0.42.jar:7.0.42]
at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5434) ~[tomcat-embed-core-7.0.42.jar:7.0.42]
at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) ~[tomcat-embed-core-7.0.42.jar:7.0.42]
at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1560) ~[tomcat-embed-core-7.0.42.jar:7.0.42]
at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549) ~[tomcat-embed-core-7.0.42.jar:7.0.42]
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303) ~[na:1.6.0_37]
at java.util.concurrent.FutureTask.run(FutureTask.java:139) ~[na:1.6.0_37]
at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886) ~[na:1.6.0_37]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:909) ~[na:1.6.0_37]
at java.lang.Thread.run(Thread.java:662) [na:1.6.0_37]
```

can someone please help me!!
thanks.

**Comment by wvanderdeijl** [comment]
Hi , I am facing the same problem , did you get some workaround for the same
